#!/bin/bash
set -x

function tar_3rd_party() {
  cleanup=$1

  clone_hypre

  if [ $cleanup -eq 1 ]; then
    tar --exclude=hypre/.git -cvzf hypre.tgz hypre/
  else
    tar -cvzf hypre.tgz hypre/
  fi

  if [ $? -ne 0 ]; then
    echo "Failed to creare a .tar out of hypre."
    exit 1
  fi
  mv hypre.tgz ../3rd_party/

  clone_nek
  clone_gslib
  clone_parrsb

  if [ $cleanup -eq 1 ]; then
    tar --exclude=nek5000/.git -cvzf nek5000.tgz nek5000/
  else
    tar -cvzf nek5000.tgz nek5000/
  fi

  if [ $? -ne 0 ]; then
    echo "Failed to creare a .tar out of nek5000."
    exit 1
  fi
  mv nek5000.tgz ../3rd_party/

  clone_occa

  if [ $cleanup -eq 1 ]; then
    tar --exclude=occa/.git -cvzf occa.tgz occa/
  else
    tar -cvzf occa.tgz occa/
  fi

  if [ $? -ne 0 ]; then
    echo "Failed to creare a .tar out of occa."
    exit 1
  fi
  mv occa.tgz ../3rd_party/

  clone_libp

  if [ $cleanup -eq 1 ]; then
    rm -rf libparanumal/nodes/tet*
    rm -rf libparanumal/nodes/tri*
    rm -rf libparanumal/meshes
    rm -rf libparanumal/benchmarks
    tar --exclude=libparanumal/.git -cvzf libparanumal.tgz libparanumal/
  else
    tar -cvzf libparanumal.tgz libparanumal/
  fi

  if [ $? -ne 0 ]; then
    echo "Failed to creare a .tar out of libparanumal."
    exit 1
  fi
  mv libparanumal.tgz ../3rd_party/

}

function tar_nekrs() {
  mkdir nekRS
  cp -r ../3rd_party ../scripts ../CMake*.txt ../examples \
    ../install_*.cmake ../LICENSE ../make* ../README* ../RELEASE* ../src ../okl ../config nekRS
  tar --exclude=.git -cvzf nekrs.tar.gz nekRS
  if [ $? -ne 0 ]; then
    echo "Failed to creare a .tar out of nekrs."
    exit 1
  fi
  mv nekrs.tar.gz ../

  cd ..
  rm -rf 3rd_party/*.tgz
  rm -rf .package
}

NEKRS_SRC_THIRD_PARTY_DIR=`pwd`/3rd_party
. ./3rd_party/3rd_party.version

# Exit if being sourced
$(return >/dev/null 2>&1)
if [ $? -eq 0 ]; then
  return 0
fi

mkdir -p .package
cd .package

tar_3rd_party 1
tar_nekrs
