#!/bin/bash
set -e -a

: ${NRSCONFIG_NOBUILD:=0}

cmd="cmake -S . -B build -Wfatal-errors $@" 
echo $cmd
eval $cmd 
if [ $? -eq 0 ] && [ ${NRSCONFIG_NOBUILD} -eq 0 ]; then
  cmd="cmake --build ./build --target install -j8" 
  echo ""    
  echo $cmd   
  read -p "Press ENTER to continue or ctrl-c to cancel"

  eval $cmd
  if [ $? -eq 0 ]; then
    echo ""
    echo -e "\033[35mHooray! You're all set. The installation is complete.\033[m"
    echo ""
  fi
fi
