name: parRSB tests
on:
  push:
    branch: [main, next]
  pull_request:
    branch: [main, next]
env:
  GITHUB.TOKEN: ${{ secrets.token }}
  PARRSB_CI: parRSB-github-ci
  EXAMPLESDIR: build/examples
jobs:
  parRSB:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [box_2x2x2, pyramid, tgv, e3q, solid, ethier, vortex, expansion]
        np: [1, 2, 3, 4]
      fail-fast: false
    name: "${{ matrix.test }}, NP = ${{ matrix.np }}"
    env:
      GSVER: 1.0.7
      CC: mpicc
    steps:
      - uses: actions/checkout@v3
      - name: Install apt dependencies
        shell: bash
        run: |
          sudo apt -y update
          sudo apt install -y mpich libmpich-dev
          sudo apt install -y libblas-dev liblapack-dev
      - name: Build parRSB and clone tests
        shell: bash
        run: |
          # Build gslib
          git clone https://github.com/Nek5000/gslib.git
          make -C gslib -j4

          # Build parRSB
          export GSLIBPATH=`pwd`/gslib/build/
          make -j4 examples

          # Clone tests
          git clone https://github.com/thilinarmtb/${PARRSB_CI}.git

          # For MPI
          echo "localhost:4" > hostfile
      - name: gencon
        shell: bash
        run: |
          cp hostfile ${EXAMPLESDIR}/gencon ${PARRSB_CI}/${{ matrix.test }}
          cd ${PARRSB_CI}/${{ matrix.test }}

          tol=(`cat test.txt | grep tol`); tol=${tol[2]}
          mpirun -np ${{ matrix.np }} --hostfile hostfile ./gencon \
            --mesh ${{ matrix.test }} --tol=${tol} --dump=0 --test=1
      - name: genmap-lanczos
        if: always()
        shell: bash
        run: |
          export PARRSB_RSB_PRE=0
          export PARRSB_RSB_ALGO=0

          cp hostfile ${EXAMPLESDIR}/genmap ${PARRSB_CI}/${{ matrix.test }}
          cd ${PARRSB_CI}/${{ matrix.test }}

          tol=(`cat test.txt | grep tol`); tol=${tol[2]}
          mpirun -np ${{ matrix.np }} --hostfile hostfile ./genmap \
            --mesh ${{ matrix.test }} --tol=${tol} --dump=0 --test=1
      - name: genmap-mg-factor-2
        if: always()
        shell: bash
        run: |
          export PARRSB_RSB_PRE=0
          export PARRSB_RSB_ALGO=1
          export PARRSB_RSB_MG_FACTOR=2

          cp hostfile ${EXAMPLESDIR}/genmap ${PARRSB_CI}/${{ matrix.test }}
          cd ${PARRSB_CI}/${{ matrix.test }}

          tol=(`cat test.txt | grep tol`); tol=${tol[2]}
          mpirun -np ${{ matrix.np }} --hostfile hostfile ./genmap \
            --mesh ${{ matrix.test }} --tol=${tol} --dump=0 --test=1
      - name: genmap-mg-factor-4
        if: always()
        shell: bash
        run: |
          export PARRSB_RSB_PRE=0
          export PARRSB_RSB_ALGO=1
          export PARRSB_RSB_MG_FACTOR=4

          cp hostfile ${EXAMPLESDIR}/genmap ${PARRSB_CI}/${{ matrix.test }}
          cd ${PARRSB_CI}/${{ matrix.test }}

          tol=(`cat test.txt | grep tol`); tol=${tol[2]}
          mpirun -np ${{ matrix.np }} --hostfile hostfile ./genmap \
            --mesh ${{ matrix.test }} --tol=${tol} --dump=0 --test=1
      - name: genmap-mg-factor-4-smooth
        if: always()
        shell: bash
        run: |
          export PARRSB_RSB_PRE=0
          export PARRSB_RSB_ALGO=1
          export PARRSB_RSB_MG_FACTOR=4
          export PARRSB_RSB_MG_SMOOTH_AGGREGATION=1

          cp hostfile ${EXAMPLESDIR}/genmap ${PARRSB_CI}/${{ matrix.test }}
          cd ${PARRSB_CI}/${{ matrix.test }}

          tol=(`cat test.txt | grep tol`); tol=${tol[2]}
          mpirun -np ${{ matrix.np }} --hostfile hostfile ./genmap \
            --mesh ${{ matrix.test }} --tol=${tol} --dump=0 --test=1
