language: c

before_install:
   - export ROOT_DIR=`pwd`
   - sudo apt-get update -qq
   - sudo apt-get install -y libmpich-dev mpich 

env:
  matrix:
    - TEST=crystal_test            NP=2
    - TEST=findpts_el_2_test       NP=2
    - TEST=findpts_el_2_test2      NP=2
    - TEST=findpts_el_3_test       NP=2
    - TEST=findpts_el_3_test2      NP=2
    - TEST=findpts_el_2_test2      NP=2
    - TEST=findpts_local_test      NP=2
    - TEST=findpts_test            NP=2
    - TEST=findpts_test_ms         NP=2
    - TEST=gs_test                 NP=2
    - TEST=gs_test_gop_nonblocking NP=2
    - TEST=gs_test_gop_blocking    NP=2
    - TEST=gs_unique_test          NP=2
    - TEST=lob_bnd_test            NP=2
    - TEST=obbox_test              NP=2
    - TEST=poly_test               NP=2
    - TEST=sarray_sort_test        NP=2
    - TEST=sarray_transfer_test    NP=2
    - TEST=sort_test               NP=2
    - TEST=sort_test2              NP=2

install: true

script:
  - cd $ROOT_DIR
  - make NBC=1 CC=mpicc tests/$TEST
  - mpiexec -np $NP ./tests/$TEST
