set(BLASLAPACK_DIR ${CMAKE_CURRENT_SOURCE_DIR}/3rd_party/BlasLapack)

set(BLASLAPACK_SOURCES
        ${BLASLAPACK_DIR}/dasum.f
        ${BLASLAPACK_DIR}/daxpy.f
        ${BLASLAPACK_DIR}/dbdsqr.f
        ${BLASLAPACK_DIR}/dcabs1.f
        ${BLASLAPACK_DIR}/dcopy.f
        ${BLASLAPACK_DIR}/ddot.f
        ${BLASLAPACK_DIR}/dgebak.f
        ${BLASLAPACK_DIR}/dgebal.f
        ${BLASLAPACK_DIR}/dgebd2.f
        ${BLASLAPACK_DIR}/dgebrd.f
        ${BLASLAPACK_DIR}/dgecon.f
        ${BLASLAPACK_DIR}/dgeev.f
        ${BLASLAPACK_DIR}/dgehd2.f
        ${BLASLAPACK_DIR}/dgehrd.f
        ${BLASLAPACK_DIR}/dgelq2.f
        ${BLASLAPACK_DIR}/dgelqf.f
        ${BLASLAPACK_DIR}/dgels.f
        ${BLASLAPACK_DIR}/dgelss.f
        ${BLASLAPACK_DIR}/dgemm.f
        ${BLASLAPACK_DIR}/dgemv.f
        ${BLASLAPACK_DIR}/dgeqr2.f
        ${BLASLAPACK_DIR}/dgeqrf.f
        ${BLASLAPACK_DIR}/dger.f
        ${BLASLAPACK_DIR}/dgesvd.f
        ${BLASLAPACK_DIR}/dgesv.f
        ${BLASLAPACK_DIR}/dgetf2.f
        ${BLASLAPACK_DIR}/dgetrf.f
        ${BLASLAPACK_DIR}/dgetri.f
        ${BLASLAPACK_DIR}/dgetrs.f
        ${BLASLAPACK_DIR}/dhseqr.f
        ${BLASLAPACK_DIR}/dlabad.f
        ${BLASLAPACK_DIR}/dlabrd.f
        ${BLASLAPACK_DIR}/dlacon.f
        ${BLASLAPACK_DIR}/dlacpy.f
        ${BLASLAPACK_DIR}/dladiv.f
        ${BLASLAPACK_DIR}/dlae2.f
        ${BLASLAPACK_DIR}/dlaev2.f
        ${BLASLAPACK_DIR}/dlahqr.f
        ${BLASLAPACK_DIR}/dlahrd.f
        ${BLASLAPACK_DIR}/dlaln2.f
        ${BLASLAPACK_DIR}/dlamch.f
        ${BLASLAPACK_DIR}/dlange.f
        ${BLASLAPACK_DIR}/dlanhs.f
        ${BLASLAPACK_DIR}/dlanst.f
        ${BLASLAPACK_DIR}/dlansy.f
        ${BLASLAPACK_DIR}/dlanv2.f
        ${BLASLAPACK_DIR}/dlapy2.f
        ${BLASLAPACK_DIR}/dlarfb.f
        ${BLASLAPACK_DIR}/dlarf.f
        ${BLASLAPACK_DIR}/dlarfg.f
        ${BLASLAPACK_DIR}/dlarft.f
        ${BLASLAPACK_DIR}/dlarfx.f
        ${BLASLAPACK_DIR}/dlartg.f
        ${BLASLAPACK_DIR}/dlas2.f
        ${BLASLAPACK_DIR}/dlascl.f
        ${BLASLAPACK_DIR}/dlaset.f
        ${BLASLAPACK_DIR}/dlasq1.f
        ${BLASLAPACK_DIR}/dlasq2.f
        ${BLASLAPACK_DIR}/dlasq3.f
        ${BLASLAPACK_DIR}/dlasq4.f
        ${BLASLAPACK_DIR}/dlasq5.f
        ${BLASLAPACK_DIR}/dlasq6.f
        ${BLASLAPACK_DIR}/dlasr.f
        ${BLASLAPACK_DIR}/dlasrt.f
        ${BLASLAPACK_DIR}/dlassq.f
        ${BLASLAPACK_DIR}/dlasv2.f
        ${BLASLAPACK_DIR}/dlaswp.f
        ${BLASLAPACK_DIR}/dlatrd.f
        ${BLASLAPACK_DIR}/dlatrs.f
        ${BLASLAPACK_DIR}/dnrm2.f
        ${BLASLAPACK_DIR}/dorg2l.f
        ${BLASLAPACK_DIR}/dorg2r.f
        ${BLASLAPACK_DIR}/dorgbr.f
        ${BLASLAPACK_DIR}/dorghr.f
        ${BLASLAPACK_DIR}/dorgl2.f
        ${BLASLAPACK_DIR}/dorglq.f
        ${BLASLAPACK_DIR}/dorgql.f
        ${BLASLAPACK_DIR}/dorgqr.f
        ${BLASLAPACK_DIR}/dorgtr.f
        ${BLASLAPACK_DIR}/dorm2r.f
        ${BLASLAPACK_DIR}/dormbr.f
        ${BLASLAPACK_DIR}/dorml2.f
        ${BLASLAPACK_DIR}/dormlq.f
        ${BLASLAPACK_DIR}/dormqr.f
        ${BLASLAPACK_DIR}/dpbtf2.f
        ${BLASLAPACK_DIR}/dpbtrf.f
        ${BLASLAPACK_DIR}/dpbtrs.f
        ${BLASLAPACK_DIR}/dposv.f
        ${BLASLAPACK_DIR}/dpotf2.f
        ${BLASLAPACK_DIR}/dpotrf.f
        ${BLASLAPACK_DIR}/dpotrs.f
        ${BLASLAPACK_DIR}/drot.f
        ${BLASLAPACK_DIR}/drscl.f
        ${BLASLAPACK_DIR}/dscal.f
        ${BLASLAPACK_DIR}/dsteqr.f
        ${BLASLAPACK_DIR}/dsterf.f
        ${BLASLAPACK_DIR}/dstev.f
        ${BLASLAPACK_DIR}/dswap.f
        ${BLASLAPACK_DIR}/dsyev.f
        ${BLASLAPACK_DIR}/dsygs2.f
        ${BLASLAPACK_DIR}/dsygst.f
        ${BLASLAPACK_DIR}/dsygv.f
        ${BLASLAPACK_DIR}/dsymm.f
        ${BLASLAPACK_DIR}/dsymv.f
        ${BLASLAPACK_DIR}/dsyr2.f
        ${BLASLAPACK_DIR}/dsyr2k.f
        ${BLASLAPACK_DIR}/dsyr.f
        ${BLASLAPACK_DIR}/dsyrfs.f
        ${BLASLAPACK_DIR}/dsyrk.f
        ${BLASLAPACK_DIR}/dsytd2.f
        ${BLASLAPACK_DIR}/dsytrd.f
        ${BLASLAPACK_DIR}/dsytrs.f
        ${BLASLAPACK_DIR}/dtbsv.f
        ${BLASLAPACK_DIR}/dtrevc.f
        ${BLASLAPACK_DIR}/dtrmm.f
        ${BLASLAPACK_DIR}/dtrmv.f
        ${BLASLAPACK_DIR}/dtrsm.f
        ${BLASLAPACK_DIR}/dtrsv.f
        ${BLASLAPACK_DIR}/dtrti2.f
        ${BLASLAPACK_DIR}/dtrtri.f
        ${BLASLAPACK_DIR}/dzasum.f
        ${BLASLAPACK_DIR}/dzsum1.f
        ${BLASLAPACK_DIR}/idamax.f
        ${BLASLAPACK_DIR}/ieeeck.f
        ${BLASLAPACK_DIR}/ilaenv.f
        ${BLASLAPACK_DIR}/izamax.f
        ${BLASLAPACK_DIR}/izmax1.f
        ${BLASLAPACK_DIR}/lsame.f
        ${BLASLAPACK_DIR}/xerbla.f
        ${BLASLAPACK_DIR}/zaxpy.f
        ${BLASLAPACK_DIR}/zcopy.f
        ${BLASLAPACK_DIR}/zdotc.f
        ${BLASLAPACK_DIR}/zdotu.f
        ${BLASLAPACK_DIR}/zdrscl.f
        ${BLASLAPACK_DIR}/zdscal.f
        ${BLASLAPACK_DIR}/zgecon.f
        ${BLASLAPACK_DIR}/zgemm.f
        ${BLASLAPACK_DIR}/zgeru.f
        ${BLASLAPACK_DIR}/zgetf2.f
        ${BLASLAPACK_DIR}/zgetrf.f
        ${BLASLAPACK_DIR}/zlacon.f
        ${BLASLAPACK_DIR}/zladiv.f
        ${BLASLAPACK_DIR}/zlaswp.f
        ${BLASLAPACK_DIR}/zlatrs.f
        ${BLASLAPACK_DIR}/zscal.f
        ${BLASLAPACK_DIR}/zswap.f
        ${BLASLAPACK_DIR}/ztrsm.f
        ${BLASLAPACK_DIR}/ztrsv.f)