set(ELLIPTIC_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/elliptic)

set(ELLIPTIC_SOURCES
        ${ELLIPTIC_SOURCE_DIR}/linearSolver/PCG.cpp
        ${ELLIPTIC_SOURCE_DIR}/linearSolver/PGMRES.cpp
        ${ELLIPTIC_SOURCE_DIR}/amgSolver/amgx/AMGX.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticApplyMask.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticBuildContinuous.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticUpdateJacobi.cpp
        ${ELLIPTIC_SOURCE_DIR}/registerEllipticKernels.cpp
        ${ELLIPTIC_SOURCE_DIR}/registerEllipticPreconditionerKernels.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticBuildPreconditionerKernels.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticBuildMultigridLevelFine.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticBuildMultigridLevel.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticMultiGridUpdateLambda.cpp
        ${ELLIPTIC_SOURCE_DIR}/optimalCoeffs.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticMultiGridLevel.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticMultiGridLevelSetup.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticMultiGridSchwarz.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticMultiGridSetup.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticOperator.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticPreconditioner.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticPreconditionerSetup.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticSolutionProjection.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticSolve.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticOgs.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticSetup.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticUpdatePCG.cpp
        ${ELLIPTIC_SOURCE_DIR}/SEMFEMSolver.cpp
        ${ELLIPTIC_SOURCE_DIR}/SEMFEMSolverBuild.cpp
        ${ELLIPTIC_SOURCE_DIR}/MGSolver/coarseLevel.cpp
        ${ELLIPTIC_SOURCE_DIR}/MGSolver/level.cpp
        ${ELLIPTIC_SOURCE_DIR}/MGSolver/MGSolver.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticZeroMean.cpp)
