set(HYPRE_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/3rd_party/hypre)

file(MAKE_DIRECTORY ${CMAKE_INSTALL_PREFIX}/include)
set(HYPRE_INCLUDE_DIR ${CMAKE_INSTALL_PREFIX}/include)
set(HYPRE_C_FLAGS "${CMAKE_C_FLAGS_RELWITHDEBINFO}")
set(HYPRE_CXX_FLAGS "${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
set(HYPRE_SHARED_LINKER_FLAGS ${CMAKE_SHARED_LINKER_FLAGS})

ExternalProject_Add(
    HYPRE_BUILD
    SOURCE_DIR ${HYPRE_SOURCE_DIR}
    SOURCE_SUBDIR "src"
    BUILD_ALWAYS ON
    CMAKE_ARGS  -DHYPRE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} 
                -DHYPRE_ENABLE_SHARED=ON
                -DHYPRE_ENABLE_MIXEDINT=ON
                -DHYPRE_ENABLE_BIGINT=ON
                -DHYPRE_ENABLE_SINGLE=OFF
                -DCMAKE_CXX_VISIBILITY_PRESET=hidden
                -DCMAKE_INSTALL_LIBDIR=${CMAKE_INSTALL_PREFIX}/lib
                -DCMAKE_C_VISIBILITY_PRESET=hidden
                -DCMAKE_BUILD_TYPE=RelWithDebInfo
                -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
                -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
                -DCMAKE_SHARED_LINKER_FLAGS=${HYPRE_SHARED_LINKER_FLAGS}
                -DCMAKE_CXX_FLAGS_RELWITHDEBINFO=${HYPRE_CXX_FLAGS}
                -DCMAKE_C_FLAGS_RELWITHDEBINFO=${HYPRE_C_FLAGS}
)
