include(examples_manifest.cmake)

foreach(F IN LISTS EXAMPLE_FILES)
    FILE(RELATIVE_PATH REL_F ${CURRENT_LIST_DIR} ${F})
    set(SOURCE ${F})
    set(DEST ${INSTALL_PREFIX}/${REL_F})
    if(NOT EXISTS ${DEST} OR ${SOURCE} IS_NEWER_THAN ${DEST})
        message(STATUS "Installing: ${DEST}")
        configure_file(${SOURCE} ${DEST} COPYONLY)
    else()
        message(STATUS "Up-to-date: ${DEST}")
    endif()
endforeach()
