file(GLOB EXAMPLE_FILES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}/examples)
foreach(FILE IN LISTS EXAMPLE_FILES)
    set(SOURCE ${CMAKE_CURRENT_SOURCE_DIR}/examples/${FILE})
    set(DEST ${CMAKE_INSTALL_PREFIX}/examples/${FILE})
    if(NOT EXISTS ${DEST} OR ${SOURCE} IS_NEWER_THAN ${DEST})
        message(NOTIFY "Installing: ${DEST}")
        configure_file(${SOURCE} ${DEST} COPYONLY)
    else()
        message(NOTIFY "Up-to-date: ${DEST}")
    endif()
endforeach()