#!/bin/bash

ulimit -s unlimited 2>/dev/null
export NEKRS_HOME=${NEKRS_HOME:="`dirname "$0"`/../"}

if [ $# -eq 0 ] || [ $# -lt 2 ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo "usage: ${0##*/} casename #tasks [args]"
  exit 1
fi
mpirun -np $2 $NEKRS_HOME/bin/nekrs --setup $1 ${@:3} 
