#!/bin/bash
set -e

if [ $# -ne 1 ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo "What manual page do you want?"
  echo "    par"
  echo "    env"
  exit 1
fi

case $1 in 
  "par")
  cat $NEKRS_HOME/doc/parHelp.txt
  ;;
  "env")
  cat $NEKRS_HOME/doc/envHelp.txt
  ;;
esac

exit 0
