#!/bin/bash
set -e
source $NEKRS_HOME/bin/nrsqsub_utils

setup $# 0 

if [ $# -eq 0 ] || [ $# -lt 2 ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo "usage: ${0##*/} casename #tasks [args]"
  exit 1
fi
mpirun -np $2 $bin --setup $1 ${@:3} 
