#!/bin/bash
set -e

: ${QUEUE:="batch"}

source $NEKRS_HOME/bin/nrsqsub_utils
setup $# 1

gpu_per_node=6
cores_per_socket=21
let nn=$nodes*$gpu_per_node
let ntasks=nn
backend=CUDA

if [ $CPUONLY -eq 1 ]; then
  backend=SERIAL
  nn=$nodes*$gpu_per_node
  let nn=2*$nodes
  let ntasks=$nn*$cores_per_socket
fi

chk_case $ntasks


export ROMIO_HINTS="$(pwd)/.romio_hint"
if [ ! -f "$ROMIO_HINTS" ]; then
  echo "romio_no_indep_rw true"   >$ROMIO_HINTS
  echo "romio_cb_write enable"   >>$ROMIO_HINTS
  echo "romio_ds_write enable"   >>$ROMIO_HINTS
  echo "romio_cb_read enable"    >>$ROMIO_HINTS
  echo "romio_ds_read enable"    >>$ROMIO_HINTS
  echo "cb_buffer_size 16777216" >>$ROMIO_HINTS
  echo "cb_config_list *:1"      >>$ROMIO_HINTS
fi

# sbatch
SFILE=s.bin
echo "#!/bin/bash" > $SFILE
echo "#BSUB -P $PROJ_ID" >>$SFILE
echo "#BSUB -J $jobname" >>$SFILE
echo "#BSUB -alloc_flags NVME" >>$SFILE
echo "#BSUB -W $time" >>$SFILE
echo "#BSUB -nnodes $qnodes" >>$SFILE

echo "" >> $SFILE
echo "export CPUONLY=$CPUONLY" >> $SFILE
echo "export NEKRS_HOME=$NEKRS_HOME" >> $SFILE
echo "export NEKRS_CACHE_BCAST=$NEKRS_CACHE_BCAST" >> $SFILE
echo "export NEKRS_GPU_MPI=1" >> $SFILE
echo "module load DefApps-2023" >> $SFILE
echo "if [ \$CPUONLY -eq 1 ]; then" >> $SFILE
echo "  module load xl" >> $SFILE
echo "  XL_HOME=\"\$OLCF_XLC_ROOT\"" >> $SFILE
echo "  export OCCA_CXX=\"\$XL_HOME/bin/xlc++\" " >> $SFILE
echo "  export OCCA_CXXFLAGS=\"-O3 -qarch=pwr9 -qhot\" " >> $SFILE
echo "  export OCCA_LDFLAGS=\"\$XL_HOME/lib/libibmc++.a\"" >> $SFILE
echo "fi" >> $SFILE

echo "module load cmake" >> $SFILE # 3.27.7
echo "module load gcc/9.1.0 cuda/11.0.3" >> $SFILE
echo "module list" >> $SFILE

echo "" >> $SFILE
echo "# work-around for barrier issue" >> $SFILE
echo "export OMPI_MCA_coll_ibm_collselect_mode_barrier=failsafe" >> $SFILE

echo "# optimize for BW" >> $SFILE
echo "export PAMI_ENABLE_STRIPING=1" >> $SFILE
echo "export PAMI_IBV_ADAPTER_AFFINITY=1" >> $SFILE
echo "export PAMI_IBV_DEVICE_NAME=\"mlx5_0:1,mlx5_3:1\"" >> $SFILE
echo "export PAMI_IBV_DEVICE_NAME_1=\"mlx5_3:1,mlx5_0:1\"" >> $SFILE
echo "export OMPI_MCA_io=romio321" >> $SFILE
echo "export ROMIO_HINTS=\"$(pwd)/.romio_hint\"" >> $SFILE

echo "" >> $SFILE

# repeat computation in user s.bin file for better readability
echo "bin=\$NEKRS_HOME/bin/nekrs" >> $SFILE
echo "nsessions=$nsessions" >> $SFILE
echo "case=$1" >> $SFILE
echo "case=\"\${case%.*}\"" >> $SFILE
echo "if [ "\$nsessions" -gt 1 ] 2> /dev/null; then" >> $SFILE
echo "  case=\$case.sess" >> $SFILE
echo "fi" >>$SFILE
echo "nodes=$2" >> $SFILE
echo "gpu_per_node=6" >> $SFILE
echo "cores_per_socket=21" >> $SFILE
echo "let nn=\$nodes*\$gpu_per_node" >> $SFILE
echo "let ntasks=nn" >> $SFILE
echo "backend=CUDA" >> $SFILE

echo "" >> $SFILE

echo "if [ \$CPUONLY -eq 1 ]; then" >> $SFILE
echo "  backend=CPU" >> $SFILE
echo "  let nn=2*\$nodes" >> $SFILE
echo "  let ntasks=\$nn*\$cores_per_socket" >> $SFILE
echo "fi " >> $SFILE

echo "" >> $SFILE

echo "export NVME_HOME=\"/mnt/bb/$USER/\"" >> $SFILE
echo "if [ \$NEKRS_CACHE_BCAST -eq 1 ]; then" >> $SFILE
echo "  export NEKRS_LOCAL_TMP_DIR=\$NVME_HOME" >> $SFILE
echo "fi" >> $SFILE
echo "" >> $SFILE


if [ $RUN_ONLY -eq 0 ]; then
  echo -e "\n# precompilation" >>$SFILE
  CMD_build="jsrun --smpiargs='-gpu' -X 1 -n\$gpu_per_node -r\$gpu_per_node -a1 -c4 -g1 -b rs -d packed \$bin --setup \$case_tmp --backend \$backend --device-id 0 $extra_args --build-only \$ntasks_tmp"
  add_build_CMD "$SFILE" "$CMD_build" "$ntasks"
fi

if [ $BUILD_ONLY -eq 0 ]; then
  link_neknek_logfile "$SFILE"
  echo -e "\n# actual run" >>$SFILE
  echo "if [ \$CPUONLY -eq 1 ]; then" >> $SFILE
  echo "  jsrun -X 1 -n\$nn -a\$cores_per_socket -c\$cores_per_socket -g0 -b packed:1 -d packed \$bin --setup \$case --backend \$backend $extra_args" >> $SFILE
  echo "else" >> $SFILE
  echo "  jsrun --smpiargs='-gpu' -X 1 -n\$nn -r\$gpu_per_node -a1 -c4 -g1 -b rs -d packed \$bin --setup \$case --backend \$backend --device-id 0 $extra_args" >> $SFILE
  echo "fi" >> $SFILE
fi

bsub -q $QUEUE $SFILE

# clean-up
rm -rf $SFILE $ROMIO_HINTS
