#!/bin/bash
set -e

: ${QUEUE:="gpu"}

source $NEKRS_HOME/bin/nrsqsub_utils
setup $# 1

gpu_per_node=4
let cores_per_numa=24/4
let cores_per_task=2*$cores_per_numa
let nn=$nodes*$gpu_per_node
let ntasks=nn
backend=CUDA

chk_case $ntasks

# romio setup
export ROMIO_HINTS="$(pwd)/.romio_hint"
if [ ! -f "$ROMIO_HINTS" ]; then
  echo "romio_no_indep_rw true"     >$ROMIO_HINTS
  echo "cb_buffer_size 67108864"   >>$ROMIO_HINTS
  echo "romio_cb_alltoall disable" >>$ROMIO_HINTS
  echo "romio_cb_read enable"      >>$ROMIO_HINTS
  echo "romio_cb_write enable"     >>$ROMIO_HINTS
  echo "romio_ds_read disable"     >>$ROMIO_HINTS
  echo "romio_ds_write disable"    >>$ROMIO_HINTS
  echo "IBM_largeblock_io true"    >>$ROMIO_HINTS
  echo "cb_config_list *:1"        >>$ROMIO_HINTS
fi

# sbatch
SFILE=s.bin
echo "#!/bin/bash" > $SFILE
echo "#SBATCH -A $PROJ_ID" >>$SFILE
echo "#SBATCH -J $jobname" >>$SFILE
echo "#SBATCH -o %x-%j.out" >>$SFILE
echo "#SBATCH -t ${time}:00" >>$SFILE
echo "#SBATCH -N $qnodes" >>$SFILE
echo "#SBATCH --exclusive" >>$SFILE
echo "#SBATCH --partition=$QUEUE" >>$SFILE
echo "#SBATCH --ntasks-per-node=$gpu_per_node" >>$SFILE
echo "#SBATCH --cpus-per-task=$cores_per_task" >>$SFILE
echo "#SBATCH --gres=gpu:$gpu_per_node" >> $SFILE
echo "#SBATCH --gpu-bind=closest" >>$SFILE
echo "#SBATCH --distribution=block:cyclic:fcyclic" >> $SFILE

echo "module load GCC OpenMPI Python UCX-settings/DC-CUDA CMake Ascent" >>$SFILE
echo "module list" >>$SFILE

echo "nvidia-smi" >>$SFILE
echo "export UCX_RNDV_THRESH=1024" >>$SFILE
echo "export UCX_RC_TM_ENABLE=y" >>$SFILE
echo "ucx_info -f" >>$SFILE

echo "ulimit -s unlimited " >>$SFILE
echo "export NEKRS_HOME=$NEKRS_HOME" >>$SFILE
echo "export NEKRS_GPU_MPI=1 " >>$SFILE
echo "export OOGS_ENABLE_NBC_DEVICE=1 " >>$SFILE

echo "export ROMIO_HINTS=$ROMIO_HINTS" >>$SFILE

echo "export NEKRS_CACHE_BCAST=$NEKRS_CACHE_BCAST" >> $SFILE
echo "if [ \$NEKRS_CACHE_BCAST -eq 1 ]; then" >> $SFILE
echo "  export NEKRS_LOCAL_TMP_DIR=\$TMPDIR/nrs" >> $SFILE
echo "  mkdir \$NEKRS_LOCAL_TMP_DIR" >> $SFILE
echo "fi" >> $SFILE

echo "export OMP_NUM_THREADS=\${SLURM_CPUS_PER_TASK}" >>$SFILE

if [ $RUN_ONLY -eq 0 ]; then
  echo -e "\n# precompilation" >>$SFILE
  CMD_build="srun --cpus-per-task=\${SLURM_CPUS_PER_TASK} --cpu-bind=cores $bin --backend $backend --device-id 0 --setup \$case_tmp $extra_args --build-only \$ntasks_tmp"
  add_build_CMD "$SFILE" "$CMD_build" "$ntasks"
fi

if [ $BUILD_ONLY -eq 0 ]; then
  link_neknek_logfile "$SFILE"
  echo -e "\n# actual run" >>$SFILE
  echo "srun --cpus-per-task=\${SLURM_CPUS_PER_TASK} --cpu-bind=cores $bin --backend $backend --device-id 0 $extra_args --setup $case" >>$SFILE
fi
sbatch $SFILE

# clean-up
rm -rf $ROMIO_HINTS
