#!/bin/bash
set -a

if [ "$1" == "nek" ]; then
git rm -rf 3rd_party/nek5000 3rd_party/nek5000_parRSB 3rd_party/nek5000_gslib
git commit -m 'remove nek'
git subtree add --prefix 3rd_party/nek5000 https://github.com/Nek5000/nek5000.git master --squash
git subtree add --prefix 3rd_party/nek5000_parRSB https://github.com/Nek5000/parRSB.git master --squash
git subtree add --prefix 3rd_party/nek5000_gslib https://github.com/Nek5000/gslib.git master --squash
rm -rf 3rd_party/nek5000/tools 3rd_party/nek5000/run 3rd_party/nek5000/examples 3rd_party/nek5000/short_tests
git reset HEAD~4 --soft
git add -u
git commit -m 'import latest nek'
elif [ "$1" == "hypre" ]; then
git rm -rf 3rd_party/hypre
git commit -m 'remove hypre'
git subtree add --prefix 3rd_party/hypre https://github.com/hypre-space/hypre.git nekRS --squash
rm -rf 3rd_party/hypre/src/examples 3rd_party/hypre/src/docs 3rd_party/hypre/src/test
git reset HEAD~2 --soft
git add -u
git commit -m 'import latest hypre'
else
echo "$1 not found"
fi
