# cvode
function(add_cvode)
  # workaround to resolve name conflict (used be OCCA and CVODE)
  set(ENABLE_CUDA ${OCCA_CUDA_ENABLED})
  set(ENABLE_HIP ${OCCA_HIP_ENABLED})
  set(ENABLE_OPENCL ${OCCA_OPENCL_ENABLED})

  if(OCCA_OPENCL_ENABLED)
    message(FATAL_ERROR "CVODE + OPENCL is not currently supported!")
  endif()
  if(OCCA_DPCPP_ENABLED)
    message(FATAL_ERROR "CVODE + DPCPP is not currently supported!")
  endif()
  if(OCCA_HIP_ENABLED)
    message(FATAL_ERROR "CVODE + HIP is not currently supported!")
  endif()

  set(ENABLE_MPI ON)
  set(BUILD_CVODE ON)
  set(BUILD_ARKODE OFF)
  set(BUILD_CVODES OFF)
  set(BUILD_IDA OFF)
  set(BUILD_IDAS OFF)
  set(BUILD_KINSOL OFF)
  set(EXAMPLES_ENABLE_C OFF)
  set(EXAMPLES_ENABLE_CXX OFF)
  if(OCCA_CUDA_ENABLED)
    set(EXAMPLES_ENABLE_CUDA OFF)
  endif()
  set(EXAMPLES_ENABLE_F2003 OFF)
  set(BUILD_TESTING OFF)
  set(BUILD_SHARED_LIBS ON)

  add_subdirectory(3rd_party/cvode)
endfunction()
